import React, { useState, useRef } from "react";
import Head from "next/head";
import { TypeAnimation } from "react-type-animation";
import { Menu, X } from "react-feather";
import SocialMedia from "../components/SocialMedia/SocialMedia";
import NavButton from "../components/Navbar/NavButton";
import ButtonPrimary from "../components/Button/ButtonPrimary";
import bg_gradient from "../assets/images/bg_gradient.png";
import img_1 from "../assets/images/img_1.jpg";
import ButtonSecondary from "../components/Button/ButtonSecondary";
import Technologies from "../components/Main/Technologies";
import ToggleTheme from "../components/Navbar/ToggleTheme";

export default function Home() {
  const [mobileMenu, setMobileMenu] = useState(false);
  const [darkToggle, setDarkToggle] = useState(false);

  const levelDesignRef = useRef(null);
  const webDeveloperRef = useRef(null);

  return (
    <div className={`relative ${darkToggle && "dark"}`}>
      <Head>
        <title>Mark Jayson Lacandula - Profile Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`absolute z-10 w-full min-h-full bg-gradient-to-r from-personal-primaryDark to-personal-primaryLight transition-all duration-300 ease-in-out ${
          mobileMenu ? "-ml-0 opacity-100" : "-ml-[100rem] opacity-0"
        }`}
      >
        <div className="backdrop-brightness-50">
          <div className="container flex flex-col justify-between min-h-screen w-[80%] relative">
            <button
              onClick={() => {
                setMobileMenu(false), (document.body.style.overflow = "auto");
              }}
              className="text-white w-12 h-12 mt-4 self-end"
            >
              <X className="w-full h-full" />
            </button>
            <ul className="flex flex-col gap-y-8 font-league-spartan font-semibold text-4xl text-white">
              <NavButton
                onClick={() =>
                  levelDesignRef.current.scrollIntoView({ behavior: "smooth" })
                }
              >
                Case Studies
              </NavButton>
              <NavButton>Contact</NavButton>
            </ul>
            <SocialMedia className="flex gap-x-4 mb-5" />
          </div>
        </div>
      </div>
      <header className="flex min-h-screen">
        <div className="w-screen object-contain relative">
          <div className="flex w-full h-full bg-gradient-to-r from-personal-backgroundLight to-personal-backgroundLighter dark:from-personal-backgroundDarker dark:to-personal-backgroundDarker absolute">
            <img
              src={bg_gradient.src}
              alt=""
              className="w-full h-full object-cover "
            />
          </div>
          <div className="flex justify-between flex-col min-h-screen dark:backdrop-brightness-50">
            <nav className="py-4">
              <div className="container w-[80%] flex justify-between relative">
                <p className="font-league-spartan font-bold text-6xl text-personal-neutralDark dark:text-personal-neutralLight tracking-tighter select-none">
                  MJL
                </p>
                <ul className="hidden tablet:flex items-center gap-x-8 font-league-spartan font-semibold text-xl text-personal-neutralDark dark:text-personal-neutralLight">
                  <NavButton
                    onClick={() =>
                      levelDesignRef.current.scrollIntoView({
                        behavior: "smooth",
                      })
                    }
                  >
                    Case Studies
                  </NavButton>
                  <NavButton>Contact</NavButton>
                  <ToggleTheme onClick={() => setDarkToggle(!darkToggle)}/>
                </ul>
                <button
                  onClick={() => {
                    setMobileMenu(true),
                      (document.body.style.overflow = "hidden");
                  }}
                  className="flex tablet:hidden"
                >
                  <Menu className="w-12 h-12 text-personal-neutralDark dark:text-white" />
                </button>
              </div>
            </nav>
            <section className="container flex flex-col items-start gap-y-4 w-[80%] relative">
              <p className="font-league-spartan font-semibold text-base tablet:text-2xl text-personal-neutralDark dark:text-personal-neutralLight">
                Hi, my name is Mark Jayson Lacandula a freelance
              </p>
              <div className="flex flex-col">
                <p className="font-league-spartan font-black text-4xl tablet:text-5xl laptop:text-7xl desktop:text-8xl text-personal-neutralDark dark:text-white tracking-tight">
                  Front-end Developer
                </p>
                <p className="font-league-spartan font-black text-4xl tablet:text-5xl laptop:text-7xl desktop:text-8xl text-personal-neutralDark dark:text-white tracking-tight">
                  & Level Designer
                </p>
              </div>
              <div className="flex gap-x-4">
                <ButtonPrimary
                  onClick={() =>
                    levelDesignRef.current.scrollIntoView({
                      behavior: "smooth",
                    })
                  }
                >
                  Web developer
                </ButtonPrimary>
                <ButtonPrimary
                  onClick={() =>
                    webDeveloperRef.current.scrollIntoView({
                      behavior: "smooth",
                    })
                  }
                >
                  Level designer
                </ButtonPrimary>
              </div>
            </section>
            <section className="container flex justify-end gap-x-4 py-4 w-[80%] relative">
              <SocialMedia className="hidden tablet:flex gap-x-4" />
            </section>
          </div>
        </div>
      </header>
      <main className="flex flex-col">
        <section
          ref={levelDesignRef}
          className="flex bg-gradient-to-b from-personal-backgroundLight to-personal-backgroundLight dark:from-personal-backgroundDarker dark:to-personal-backgroundDarker"
        >
          <div className="container flex gap-x-8 w-[80%] min-h-screen py-20 relative"></div>
        </section>
        <section
          ref={webDeveloperRef}
          className="flex bg-gradient-to-b from-personal-backgroundLight to-personal-backgroundLighter dark:from-personal-backgroundDarker dark:to-personal-backgroundDark"
        >
          <div className="container flex gap-x-8 w-[80%] min-h-screen py-20 relative"></div>
        </section>
        <section className="flex flex-col bg-gradient-to-b from-personal-backgroundLight to-personal-backgroundLighter dark:from-personal-backgroundDarker dark:to-personal-backgroundDark">
          <div className="container flex flex-col lg:flex-row gap-x-10 gap-y-20 w-[80%] py-20 relative">
            <div className="flex basis-1/2 overflow-hidden">
              <div className="flex flex-col gap-y-8 relative">
                <p className="text-9xl text-slate-300 font-league-spartan font-bold dark:text-slate-700 absolute">
                  Technologies
                </p>
                <p className="text-4xl text-personal-neutralDark font-league-spartan font-bold dark:text-personal-neutralLight z-10 mt-16">
                  Technologies used
                </p>
                <p className="text-xl text-personal-neutralDark font-league-spartan dark:text-personal-neutralLight z-10">
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                  Magni dolorum eum quasi voluptas illo laborum.
                </p>
               <Technologies/>
              </div>
            </div>
            <div className="flex justify-center items-center basis-1/2">
              <div className="flex-none w-full min-h-[30rem] max-w-[30rem] mb-10 relative z-10 before:absolute before:top-4 before:left-4 before:w-full before:h-full before:border-8 before:border-slate-300 dark:before:border-slate-700">
                <img
                  src={img_1.src}
                  alt=""
                  className="absolute z-10 inset-0 w-full h-full object-cover"
                />
                <div className="flex flex-col justify-between h-full w-full z-20 p-4 absolute">
                  <div className="flex">
                    <p className="text-4xl text-personal-neutralLight font-bold font-league-spartan">
                      I love&nbsp;
                    </p>
                    <TypeAnimation
                      sequence={[
                        "Cooking",
                        1000,
                        "Running",
                        1000,
                        "Cycling",
                        1000,
                        "Basketball",
                        1000,
                        "Music",
                        1000,
                        "Movies",
                        1000,
                        "Elay",
                        1000,
                      ]}
                      //  Replacing previous Text
                      className="text-4xl text-personal-neutralLight font-bold font-league-spartan"
                      repeat={Infinity}
                    />
                  </div>
                  <div className="flex justify-end">
                    <ButtonSecondary>Start porject together</ButtonSecondary>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section
          className="flex bg-gradient-to-b from-personal-backgroundLight to-personal-backgroundLighter dark:from-personal-backgroundDarker dark:to-personal-backgroundDark"
        >
          <div className="container flex gap-x-8 w-[80%] min-h-screen py-20 relative"></div>
        </section>
      </main>
      <footer className="flex justify-center min-h-[50vh] bg-slate-900">
        <div className="backdrop-brightness-75 flex flex-col items-center justify-center w-screen relative">
          <p className="font-league-spartan font-black text-6xl text-white tracking-tight select-none">
            MJL
          </p>
        </div>
      </footer>
    </div>
  );
}
